local turtleFuncs = require("turtleFuncs.lua")

local function mainTeaLoop()
	turtleFuncs.upX(4)
	turtleFuncs.forwardX(3)
	turtleFuncs.turnLeftX(1)
	turtle.forward()
	turtle.dropDown(1)
	turtle.forward()
	turtle.dropDown(1)
	turtle.turnRight()
	turtle.forward()
	turtle.dropDown(1)
	turtle.turnRight()
	turtle.forward()
	turtle.dropDown(1)
	turtleFuncs.forwardX(1)
	turtle.turnRight()
	turtleFuncs.forwardX(4)
	turtleFuncs.turnRightX(2)
	turtleFuncs.downX(4)
end
